.TH PYAGW3 3 "December 29, 2025" "PyAGW3 0.1.0" "Python Library"
.SH NAME
pyagw3 \- Python 3 AGWPE TCP/IP API client for packet radio
.SH SYNOPSIS
.B from pyagw3 import AGWPEClient
.PP
.B client = AGWPEClient(host="127.0.0.1", callsign="N0CALL")
.br
.B client.connect()
.SH DESCRIPTION
.B PyAGW3
is a modern Python implementation of the AGW Packet Engine (AGWPE) TCP/IP protocol client.
It supports unproto and connected mode operation, monitoring, and server queries.
.SH SEE ALSO
AGWPE TCP/IP API Tutorial (2000) by LU7DID/SV2AGW
.SH AUTHOR
Kris Kirby, KE4AHR <ke4ahr@gmail.com>
.SH COPYRIGHT
Copyright © 2025-2026 Kris Kirby, KE4AHR
License LGPL-3.0-or-later <https://gnu.org/licenses/lgpl-3.0.html>
